name: API CI
on:
  push:
    branches: ['*']
  services:
    postgres-e2e:
      image: postgres:13
      ports:
        - 5432:5432
      env:
        - POSTGRES_DB: db_e2e
        - POSTGRES_USER: felipe
        - POSTGRES_PASSWORD: admin123

jobs:
  e2e:
    runs-on: ubuntu-latest
    container:
      image: node:16
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Checkout
        uses: pnpm ci
      - name: run e2e
        run: pnpm e2e:ci
        env:
          PORT: 3000
          DATABASE_URL: postgres://felipe:admin123@postgres-e2e:5432/db_e2e
          JWT_SECRET: d124aab03a0ff7ccf98a96f0d82db7bcd1db0a9b2e9c82007e18b62be418259666ab792db8254c0fd66cb5cd30
